apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-damonx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-damonx
  template:
    metadata:
      labels:
        app: hello-damonx
    spec:
      containers:
      - name: hello-damonx
        image: damonx/hello-damonx:1.0
        ports:
        - containerPort: 8080